
export const HEARTCHECK = 'Heartcheck'
export const CONNECT = 'CONNECT'
export const DISCONNECT = 'DISCONNECT'
export const CONNECT_ACK = 'CONNECT_ACK'
export const PUBLISH = 'PUBLISH'
export const PUB_ACK = 'PUB_ACK'
// cmd
export const RECEIVE_MSG = 'user'
export const FP = 'FP'
export const FALS = 'FALS'
export const UPUI = 'UPUI'
export const GPGI = 'GPGI'
export const GPGM = 'GPGM'
export const GAM = 'GAM'
export const GC = 'GC'
export const GMI = 'GMI'
export const GKM = 'GKM'
export const GQ = 'GQ'
export const GD = 'GD'
export const MP = 'MP'
export const MS = 'MS'
export const MN = 'MN'
export const MR = 'MR'
export const RMN = 'RMN'
export const GQNUT = 'GQNUT'
export const GMURL = 'GMURL'
export const US = 'US'
export const FAR = 'FAR'
export const FRN = 'FRN'
export const FHR = 'FHR'
export const FN = 'FN'
export const MMI = 'MMI'
export const LRM = 'LRM'

export const ERROR_CODE = 500
export const SUCCESS_CODE = 200
