export default {
  SCREEN_CAPTURE_VIDEO_EDIT: 'SCREEN_CAPTURE_VIDEO_EDIT',
  SCREEN_CAPTURE_VIDEO_UPDATE: 'SCREEN_CAPTURE_VIDEO_UPDATE',
  SCREEN_CAPTURE_VIDEO_ADD: 'SCREEN_CAPTURE_VIDEO_ADD',
  SCREEN_CAPTURE_VIDEO_DELETE: 'SCREEN_CAPTURE_VIDEO_DELETE'
}
