export default {
  INSERT_DRIVE_ITEM: 'INSERT_DRIVE_ITEM',
  INSERT_YOUTUBE_ITEM: 'INSERT_YOUTUBE_ITEM',
  INSERT_GOOGLE_IMAGE: 'INSERT_GOOGLE_IMAGE',
  INSERT_GOOGLE_DRIVE: 'INSERT_GOOGLE_DRIVE',
  DELETE_VIDEO: 'DELETE_VIDEO',
  DELETE_IMAGE: 'DELETE_IMAGE'
}
