export const CoverMediaEvent = {
  COVER_MEDIA_EDIT: 'COVER_MEDIA_EDIT',
  COVER_MEDIA_UPDATE: 'COVER_MEDIA_UPDATE',
  COVER_MEDIA_ADD: 'COVER_MEDIA_ADD',
  COVER_MEDIA_DELETE: 'COVER_MEDIA_DELETE'
}
