name: Classcipe Web Actions
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to github packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Use Node.js 14.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path:  |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/cache
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build-Develop
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: yarn run build-develop
      - name: Build-Test
        if: github.ref == 'refs/heads/test' && github.event_name == 'push'
        run: yarn run build-test
      - name: Build-Production
        if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
        run: yarn run build
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}_${{ github.sha }}
          release_name: Release ${{ github.ref }} with hash ${{ github.sha }}
          draft: false
          prerelease: false
      - name: Push Images to GitHub Packages (develop)
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: zran-nz/classcipe_web/frontend
          tags: develop
          tag_with_ref: true
      - name: Push Images to GitHub Packages (test)
        if: github.ref == 'refs/heads/test' && github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: zran-nz/classcipe_web/frontend
          tags: test
          tag_with_ref: true
      - name: Push Images to GitHub Packages (prod)
        if: github.ref == 'refs/heads/prod' && github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: zran-nz/classcipe_web/frontend
          tags: production
          tag_with_ref: true
      - name: Deploy to develop server
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: |
          mkdir -p ~/.ssh
          echo "$TEST_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ubuntu@13.236.143.19
          ssh  ubuntu@13.236.143.19  'cd deployment-cloud/cc-api-cloud && ./start-ui.sh'
        env:
          TEST_SERVER_PRIVATE_KEY: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
